server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://dbpragma.c1zec6yu0aq8.us-east-2.rds.amazonaws.com:3306/powerup
    username: admin
    password: "ju4ns3b4st14n"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Reto Pragma"
appVersion: "1.0.0"
