name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: build and push to docker
        uses: docker/build-push-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      - name: Build and push Docker
        uses: docker/build-push-action@v4.1.1
        with:
          username: ${{ secrets.USERNAME_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
